/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialmediaRouteImport } from './routes/socialmedia'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as MarketingPoliticoRouteImport } from './routes/marketing-politico'
import { Route as CrcRouteImport } from './routes/crc'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewIntroRouteImport } from './routes/preview.intro'

const SocialmediaRoute = SocialmediaRouteImport.update({
  id: '/socialmedia',
  path: '/socialmedia',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingPoliticoRoute = MarketingPoliticoRouteImport.update({
  id: '/marketing-politico',
  path: '/marketing-politico',
  getParentRoute: () => rootRouteImport,
} as any)
const CrcRoute = CrcRouteImport.update({
  id: '/crc',
  path: '/crc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewIntroRoute = PreviewIntroRouteImport.update({
  id: '/preview/intro',
  path: '/preview/intro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crc': typeof CrcRoute
  '/marketing-politico': typeof MarketingPoliticoRoute
  '/performance': typeof PerformanceRoute
  '/socialmedia': typeof SocialmediaRoute
  '/preview/intro': typeof PreviewIntroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crc': typeof CrcRoute
  '/marketing-politico': typeof MarketingPoliticoRoute
  '/performance': typeof PerformanceRoute
  '/socialmedia': typeof SocialmediaRoute
  '/preview/intro': typeof PreviewIntroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crc': typeof CrcRoute
  '/marketing-politico': typeof MarketingPoliticoRoute
  '/performance': typeof PerformanceRoute
  '/socialmedia': typeof SocialmediaRoute
  '/preview/intro': typeof PreviewIntroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crc'
    | '/marketing-politico'
    | '/performance'
    | '/socialmedia'
    | '/preview/intro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crc'
    | '/marketing-politico'
    | '/performance'
    | '/socialmedia'
    | '/preview/intro'
  id:
    | '__root__'
    | '/'
    | '/crc'
    | '/marketing-politico'
    | '/performance'
    | '/socialmedia'
    | '/preview/intro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrcRoute: typeof CrcRoute
  MarketingPoliticoRoute: typeof MarketingPoliticoRoute
  PerformanceRoute: typeof PerformanceRoute
  SocialmediaRoute: typeof SocialmediaRoute
  PreviewIntroRoute: typeof PreviewIntroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/socialmedia': {
      id: '/socialmedia'
      path: '/socialmedia'
      fullPath: '/socialmedia'
      preLoaderRoute: typeof SocialmediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-politico': {
      id: '/marketing-politico'
      path: '/marketing-politico'
      fullPath: '/marketing-politico'
      preLoaderRoute: typeof MarketingPoliticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crc': {
      id: '/crc'
      path: '/crc'
      fullPath: '/crc'
      preLoaderRoute: typeof CrcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/intro': {
      id: '/preview/intro'
      path: '/preview/intro'
      fullPath: '/preview/intro'
      preLoaderRoute: typeof PreviewIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrcRoute: CrcRoute,
  MarketingPoliticoRoute: MarketingPoliticoRoute,
  PerformanceRoute: PerformanceRoute,
  SocialmediaRoute: SocialmediaRoute,
  PreviewIntroRoute: PreviewIntroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
